export enum TipoLocal {
  COMIDA = 'COMIDA',
  ROPA = 'ROPA',
  ELECTRODOMESTICOS = 'ELECTRODOMESTICOS',
  FARMACIA = 'FARMACIA',
  SERVICIOS = 'SERVICIOS',
  CARNICERIA = 'CARNICERIA',
  OTROS = 'OTROS',
}
